/* Starter library. Tuple: term, phonetic, Chinese, definition, example, research application */
const researchRows = [
  ["embodiment","/ɪmˈbɒdimənt/","具身性；身体化","定性","意义、认知与行动通过身体而形成，而非发生在脱离身体的意识中。","Embodiment is central to understanding how performers make meaning through bodily action.","说明京剧动作不是音乐之外的装饰，而是参与生成表演意义。"],
  ["lived body","/lɪvd ˈbɒdi/","生活身体；体验身体","从第一人称被生活和体验的身体，而不是被观察、测量的客观身体。","The lived body is the performer’s way of inhabiting the musical world.","分析演奏者怎样从内部体验弓、琴、重心与动作。"],
  ["body schema","/ˈbɒdi ˈskiːmə/","身体图式","身体对于自身位置、能力与运动可能性的前反思性整体把握。","Repeated practice reshapes the performer’s body schema.","解释程式训练如何沉淀为无需逐步思考的动作能力。"],
  ["body image","/ˈbɒdi ˈɪmɪdʒ/","身体意象","主体对自己身体的知觉、信念、判断和态度。","Body image should not be confused with the pre-reflective body schema.","帮助区分身体的反思性表象与实际动作组织。"],
  ["motor intentionality","/ˈməʊtə ˌɪntenʃəˈnæləti/","运动意向性","身体以“我能”的方式直接朝向行动的可能性。","Motor intentionality lets the violinist respond before explicit reflection.","分析图谱形符号导视如何直接唤起演奏动作。"],
  ["operative intentionality","/ˈɒpərətɪv ˌɪntenʃəˈnæləti/","运作意向性","在明确判断之前组织经验的深层、前反思意向结构。","Operative intentionality structures experience before conscious judgement.","解释视觉、动作与声音何以在意识分析前形成整体。"],
  ["intentionality","/ɪnˌtenʃəˈnæləti/","意向性","意识总是关于某物、朝向某物的基本结构。","Perception is intentional because it is always directed toward a world.","说明演奏经验从来不是封闭的心理状态。"],
  ["pre-reflective","/ˌpriː rɪˈflektɪv/","前反思的","在被明确思考、判断或语言化以前已经发生的经验层次。","Bodily adjustment often occurs at a pre-reflective level.","描述演奏者在说清动作之前已经完成的身体调节。"],
  ["kinaesthesia","/ˌkɪnɪsˈθiːziə/","动觉","对自身运动、张力、方向和位置变化的内在感受。","Kinaesthesia gives movement its felt dynamic quality.","用于研究演奏者如何感受京剧动作的速度、重量和流动。"],
  ["proprioception","/ˌprəʊpriəˈsepʃən/","本体感觉","无需视觉便感知身体各部分位置和运动的能力。","Proprioception guides the player’s bow arm without constant visual monitoring.","说明小提琴动作如何依靠身体内部反馈而被控制。"],
  ["sedimentation","/ˌsedɪmenˈteɪʃən/","沉积；沉淀","过去经验和习惯层层保留在当下身体与知觉之中。","Training becomes sedimented in the performer’s habitual movements.","连接长期程式训练与当下自然发生的动作。"],
  ["habitual body","/həˈbɪtʃuəl ˈbɒdi/","习惯身体","由过去练习形成、能够自动应对熟悉情境的身体。","The habitual body carries techniques acquired through repetition.","阐释演奏技术及京剧程式如何成为身体习惯。"],
  ["body-subject","/ˈbɒdi ˈsʌbdʒɪkt/","身体主体","身体不是主体使用的客体，而是感知与行动的主体本身。","The performer acts as a body-subject rather than a mind controlling a machine.","支持从“身体执行音乐”转向“身体生成音乐”。"],
  ["being-in-the-world","/ˌbiːɪŋ ɪn ðə ˈwɜːld/","在世存在","主体始终已经处在具体世界关系之中的存在方式。","Performance is a situated mode of being-in-the-world.","把演奏理解为身体、空间、乐器及他人的整体关系。"],
  ["affordance","/əˈfɔːdəns/","可供性；行动可能性","环境相对于某个行动者所提供或邀请的行动机会。","The graphic line affords a sweeping rather than a segmented gesture.","分析图形符号如何邀请某类弓法与身体路径。"],
  ["intercorporeality","/ˌɪntəkɔːpɔːriˈæləti/","身体间性","主体通过身体与他人的身体相互感知、回应并共同构成意义。","Intercorporeality emerges between actor, violinist and audience.","讨论京剧演员、演奏者与观众之间的身体共鸣。"],
  ["reversibility","/rɪˌvɜːsəˈbɪləti/","可逆性","感知者同时也可被感知，触摸者同时也是被触摸者。","Reversibility complicates the division between sensing and sensed body.","理解演奏者既操控乐器又被声音和触感反向塑造。"],
  ["the flesh","/ðə fleʃ/","肉身；世界之肉","梅洛-庞蒂晚期描述身体与世界共享的可感织体。","The flesh names the intertwining of body and world.","为身体、乐器、舞台空间相互交织提供本体论语言。"],
  ["chiasm","/ˈkaɪæzəm/","交叉；交织","主体与世界、观看与被观看之间相互嵌入的结构。","The chiasm reveals a crossing between perceiver and perceived.","描述动作观看如何转化并重组演奏者自身动作。"],
  ["phenomenological reduction","/fəˌnɒmɪnəˈlɒdʒɪkəl rɪˈdʌkʃən/","现象学还原","暂时悬置习惯判断，转向经验如何被给予和显现。","Phenomenological reduction redirects attention to how movement is experienced.","指导实践日志关注动作如何被体验，而不只解释其既定意义。"],
  ["epoché","/ˈepəkeɪ/","悬置","将关于世界的自然态度和预设暂时置于括号之中。","Epoché does not deny the world; it suspends taken-for-granted assumptions.","避免先把京剧动作机械地等同于固定音乐参数。"],
  ["lifeworld","/ˈlaɪfwɜːld/","生活世界","科学抽象之前，日常经验中直接被生活的意义世界。","Musical practice unfolds within a culturally shaped lifeworld.","强调京剧动作根植于具体文化、历史与生活实践。"],
  ["perceptual field","/pəˈseptʃuəl fiːld/","知觉场","事物在前景、背景和身体朝向中形成的整体知觉结构。","A gesture gains salience within the performer’s perceptual field.","分析舞台焦点、空间方向和动作注意如何共同组织表演。"],
  ["horizon","/həˈraɪzən/","地平线；视域","每个显现周围未被直接给予、却被共同预期的意义背景。","Every perceived gesture appears against a horizon of possible movements.","说明单一动作如何暗示前后动作、角色经历与文化知识。"],
  ["appearance","/əˈpɪərəns/","显现；呈现","对象以某种角度和方式进入经验，而非虚假表象。","Meaning arises through the manner of a gesture’s appearance.","讨论角色意义如何在具体速度、方向和张力中显现。"],
  ["temporality","/ˌtempəˈræləti/","时间性","经验由当下、保留的过去与预期的未来共同组织。","Musical temporality is lived through anticipation and retention.","分析停顿、蓄势与动作延续如何塑造音乐时间。"],
  ["spatiality","/ˌspeɪʃiˈæləti/","空间性","身体所生活和组织的方向性、关系性空间。","Bodily spatiality differs from abstract geometrical space.","把舞台空间视为行动与意义空间，而不是坐标容器。"],
  ["motility","/məʊˈtɪləti/","运动能力；能动运动性","身体主动进入、把握并重组其行动世界的能力。","Motility expresses the body’s practical grasp of its environment.","连接演奏者动作能力与图形记谱提供的路径。"],
  ["corporeality","/kɔːˌpɔːriˈæləti/","身体性","作为有形、有感和能动身体而存在的性质。","Corporeality is integral to the production of musical meaning.","概括音乐意义生成中的身体维度。"],
  ["enaction","/ɪˈnækʃən/","生成性行动；施行认知","认知通过行动者与环境的持续互动被带出来。","Meaning is enacted through the coupling of gesture, instrument and sound.","解释声音不是动作之后的产物，而在互动中共同生成。"],
  ["sensorimotor contingency","/ˌsensəriˈməʊtə kənˈtɪndʒənsi/","感觉运动偶联","感知变化与可能动作之间的规律性依赖关系。","The violinist learns sensorimotor contingencies between pressure and timbre.","分析弓压、触感反馈与音色改变间的具身关系。"],
  ["intersubjectivity","/ˌɪntəsʌbdʒekˈtɪvəti/","主体间性","经验与意义在主体之间相互理解、协商和构成。","Interpretation develops intersubjectively through rehearsal dialogue.","支持用访谈与共同排练研究意义如何协商形成。"],
  ["habitus","/ˈhæbɪtəs/","惯习","历史和社会结构沉淀为身体化倾向，使某些行动显得自然。","Jingju training produces a culturally specific bodily habitus.","解释程式动作的文化稳定性及训练来源。"],
  ["hexis","/ˈheksɪs/","身体姿态；身体惯习","社会经验体现为持久的姿态、步态、语调和身体风格。","Bodily hexis makes social history visible in posture and gait.","细化角色身份如何体现在站姿、眼神和运动方式中。"],
  ["embodied knowledge","/ɪmˈbɒdid ˈnɒlɪdʒ/","具身知识","通过实践获得并在身体能力中表现、难以完全言传的知识。","Embodied knowledge is demonstrated in skilled action rather than verbal rules.","作为京剧动作向小提琴实践转化的核心研究对象。"],
  ["tacit knowledge","/ˈtæsɪt ˈnɒlɪdʒ/","默会知识","行动者知道如何做，却难以完整陈述规则的知识。","Performers rely on tacit knowledge when adjusting a gesture in real time.","说明为何单靠文本分析无法把握全部表演知识。"],
  ["practice-led research","/ˈpræktɪs led rɪˈsɜːtʃ/","实践引领研究","以创作实践作为问题、方法及知识生产核心的研究路径。","Practice-led research treats artistic making as a mode of inquiry.","为演奏、作曲和记谱实验作为研究方法提供依据。"],
  ["practice as research","/ˈpræktɪs æz rɪˈsɜːtʃ/","实践即研究","将实践过程与成果本身视作可论证的研究贡献。","Practice as research generates knowledge through doing.","帮助说明演出与作品并非论文之外的附属成果。"],
  ["reflexivity","/ˌriːflekˈsɪvəti/","反身性","研究者持续审视自身位置、判断和介入如何影响研究。","Reflexivity requires the researcher-performer to examine her own assumptions.","指导你记录自身训练背景与选择如何塑造转译。"],
  ["situated knowledge","/ˈsɪtʃueɪtɪd ˈnɒlɪdʒ/","情境化知识","知识总从具体身体、文化位置和实践条件中产生。","Performance produces situated rather than universally neutral knowledge.","防止把个人演奏实验泛化为所有表演者的普遍经验。"],
  ["thick description","/θɪk dɪˈskrɪpʃən/","深描","把行为连同语境、意图和文化意义进行密集描述。","Thick description situates a gesture within its theatrical context.","用于记录虞姬动作而不仅是其外部运动轨迹。"],
  ["graphic notation","/ˈɡræfɪk nəʊˈteɪʃən/","图形记谱","以图形、空间、线条等非传统符号组织音乐行动的记谱方式。","Graphic notation can invite bodily interpretation rather than prescribe fixed pitches.","充当京剧动作与小提琴身体反应之间的实验媒介。"],
  ["indeterminacy","/ˌɪndɪˈtɜːmɪnəsi/","不确定性；非定限性","作品有意保留部分结果，由演奏者或情境具体实现。","Indeterminacy allows each performer to realise the score differently.","界定图形记谱开放性与演奏者能动性。"],
  ["performer agency","/pəˈfɔːmə ˈeɪdʒənsi/","演奏者能动性","演奏者主动解释、选择并塑造作品结果的能力。","The notation expands performer agency without removing compositional structure.","评估图形谱如何平衡引导与自由。"],
  ["gesture","/ˈdʒestʃə/","姿态；动作姿势","具有表达、交流或组织功能的身体运动单位。","Gesture mediates between bodily motion and musical expression.","作为京剧动作与音乐动作比较的基本分析单位。"],
  ["movement quality","/ˈmuːvmənt ˈkwɒləti/","运动质感","动作的重量、时间、流动、张力与方向等动态特征。","The same trajectory acquires new meaning through a different movement quality.","避免仅按照动作外形进行表面对照。"],
  ["dynamic form","/daɪˈnæmɪk fɔːm/","动力形式","在时间中展开、由力度与变化塑造的活态形式。","Dynamic form connects felt movement with expressive meaning.","把水袖动作的动力轨迹转化为声音结构。"],
  ["corporeal memory","/kɔːˈpɔːriəl ˈmeməri/","身体记忆","过去动作经验以姿态、感觉和行动倾向保存在身体中。","Corporeal memory becomes audible in recurring performance habits.","研究训练记忆怎样进入弓法和音色。"],
  ["re-embodiment","/ˌriː ɪmˈbɒdimənt/","再具身化","一种意义或运动结构在新的身体与媒介中重新获得实现。","Jingju movement undergoes re-embodiment in violin performance.","准确概括动作经图形谱进入演奏身体的过程。"],
  ["translation","/trænzˈleɪʃən/","转译；转换","意义在媒介、文化或符号系统之间发生带有差异的重构。","Translation here is transformative rather than mechanically equivalent.","强调京剧动作与声音之间不是一对一复制。"],
  ["transduction","/trænzˈdʌkʃən/","跨媒介转导","能量、感知或信息在不同形式之间连续转化的过程。","The score transduces visual motion into tactile and sonic response.","描述视觉线条、身体感觉和声音之间的连续转化。"],
  ["multimodality","/ˌmʌlti məʊˈdæləti/","多模态性","意义通过视觉、听觉、动作、空间等多种模式协同形成。","The project depends on multimodality across image, gesture and sound.","统摄动作观察、图形设计和音乐实践。"],
  ["sonic gesture","/ˈsɒnɪk ˈdʒestʃə/","声音姿态","在时间中具有方向、能量和形态感的声音过程。","A sonic gesture can preserve the energetic profile of a stage movement.","比较动作动力与音乐音响形态，而非固定音高对应。"],
  ["ecological perception","/ˌiːkəˈlɒdʒɪkəl pəˈsepʃən/","生态知觉","把知觉理解为行动者对环境中可供性的直接把握。","Ecological perception foregrounds action possibilities in the score.","解释演奏者如何把图形看成可做的动作。"],
  ["participant observation","/pɑːˈtɪsɪpənt ˌɒbzəˈveɪʃən/","参与式观察","研究者在参与实践的同时系统观察并记录。","Participant observation combines bodily learning with critical documentation.","适合你进入京剧训练过程收集第一人称材料。"],
  ["stimulated recall","/ˈstɪmjʊleɪtɪd rɪˈkɔːl/","刺激回忆访谈","借助录像、录音等提示参与者回忆当时的思考和感受。","Video-based stimulated recall can reveal otherwise tacit decisions.","用排练录像帮助演奏者说明当时身体反应。"],
  ["micro-phenomenology","/ˌmaɪkrəʊ fəˌnɒmɪˈnɒlədʒi/","微观现象学","通过精细访谈描述短暂经验的时间结构和感受细节。","Micro-phenomenology examines the fine grain of lived experience.","用于追问某一弓法产生前后的注意、感觉与意向变化。"],
  ["first-person account","/ˌfɜːst ˈpɜːsən əˈkaʊnt/","第一人称陈述","参与者从自身经验立场给出的描述。","First-person accounts complement external movement analysis.","作为身体经验材料，与录像的第三人称观察互补。"],
  ["triangulation","/traɪˌæŋɡjʊˈleɪʃən/","三角互证","用多种资料、方法或视角交叉检验研究解释。","Triangulation combines diaries, interviews and performance recordings.","提高实践研究论证的可信度。"],
  ["coding framework","/ˈkəʊdɪŋ ˈfreɪmwɜːk/","编码框架","用于系统标记、分类和比较质性资料的概念体系。","The coding framework tracks recurring bodily and sonic qualities.","组织实践日志、访谈与录像中的主题。"],
  ["artistic inquiry","/ɑːˈtɪstɪk ɪnˈkwaɪəri/","艺术探究","通过艺术创作提出问题、生成认识并传播研究成果。","Artistic inquiry values sensory and performative forms of knowing.","说明音乐创作何以成为严肃的知识生产方式。"]
];

const lifeRows = [
  ["articulate","/ɑːˈtɪkjʊleɪt/","清楚表达","To express an idea clearly and effectively.","She articulated her argument clearly during the supervision.","适合在导师交流中说明复杂观点。"],
  ["nuance","/ˈnjuːɑːns/","细微差别","A subtle distinction in meaning, expression or feeling.","The translation loses some of the nuance of the original gesture.","谈论概念和跨文化差异时常用。"],
  ["clarify","/ˈklærɪfaɪ/","澄清；讲明","To make something easier to understand.","Could you clarify what you mean by bodily knowledge?","用于课堂、会议和邮件提问。"],
  ["elaborate","/ɪˈlæbəreɪt/","详细说明","To explain or develop an idea in greater detail.","Could you elaborate on the methodological process?","比 explain 更适合追问细节。"],
  ["coherent","/kəʊˈhɪərənt/","连贯的","Logical, consistent and easy to understand.","The revised chapter now presents a coherent argument.","评价文章、发言或计划的结构。"],
  ["concise","/kənˈsaɪs/","简明的","Giving necessary information in few words.","Keep the abstract concise but specific.","用于学术写作和日常职场表达。"],
  ["relevant","/ˈreləvənt/","相关的","Directly connected with the matter being discussed.","This example is particularly relevant to my project.","论证材料与问题之间的联系。"],
  ["assumption","/əˈsʌmpʃən/","假设；想当然","Something accepted as true without sufficient proof.","We need to examine the assumptions behind this interpretation.","日常讨论和批判性思考中的高频词。"],
  ["perspective","/pəˈspektɪv/","视角；观点","A particular way of considering something.","From the performer’s perspective, the notation feels open-ended.","表达不同立场而不把它说成唯一事实。"],
  ["constraint","/kənˈstreɪnt/","限制条件","A limit that restricts what can be done.","Time is the main constraint on the current experiment.","用于讨论现实条件和设计边界。"],
  ["feasible","/ˈfiːzəbəl/","可行的","Possible and practical to do successfully.","A small pilot study is feasible within one semester.","评价计划是否现实。"],
  ["tentative","/ˈtentətɪv/","暂定的；试探性的","Not yet certain or final.","My tentative conclusion is that the score changes bodily attention.","表达尚未完全确认的判断。"],
  ["compelling","/kəmˈpelɪŋ/","有说服力的","Evoking strong interest or convincing belief.","The recordings provide compelling evidence of change.","评价论证、故事或艺术作品。"],
  ["ambiguous","/æmˈbɪɡjuəs/","含糊的；多义的","Open to more than one interpretation.","The instruction is deliberately ambiguous.","描述表达不清或作品开放多义。"],
  ["substantial","/səbˈstænʃəl/","大量的；实质性的","Large or important enough to matter.","The revision requires substantial changes.","比 big 或 a lot 更正式准确。"],
  ["account for","/əˈkaʊnt fɔː/","解释；考虑到","To explain or include something in a judgement.","The analysis must account for differences between performers.","构建完整解释时常用。"],
  ["draw on","/drɔː ɒn/","利用；借鉴","To use information, experience or resources.","The project draws on phenomenology and performance studies.","说明观点或实践的来源。"],
  ["point out","/pɔɪnt aʊt/","指出","To draw attention to a fact or issue.","My supervisor pointed out a gap in the argument.","比 say 更明确的日常学术表达。"],
  ["work through","/wɜːk θruː/","逐步处理","To deal carefully with a problem or material.","I need time to work through the theoretical chapter.","描述解决复杂问题的过程。"],
  ["follow up","/ˈfɒləʊ ʌp/","跟进","To take further action after an earlier event.","I will follow up by email after the meeting.","会议、邮件和事务安排中的高频词。"],
  ["prioritise","/praɪˈɒrətaɪz/","优先处理","To decide which tasks are most important.","I need to prioritise the literature review this week.","组织学习和工作计划。"],
  ["overlook","/ˌəʊvəˈlʊk/","忽视；漏看","To fail to notice or consider something.","It is easy to overlook the performer’s sensory experience.","指出论述中被忽略的部分。"],
  ["convey","/kənˈveɪ/","传达","To communicate an idea, feeling or impression.","The gesture conveys restraint rather than weakness.","讨论语言、艺术和身体表达。"],
  ["retain","/rɪˈteɪn/","保留；记住","To continue to have or remember something.","The adaptation retains the dynamic quality of the original.","既可谈记忆，也可谈作品保留特征。"],
  ["encounter","/ɪnˈkaʊntə/","遇到；遭遇","To meet or experience something unexpectedly.","I encountered this concept while reading Merleau-Ponty.","比 meet 更适合思想、困难和经验。"],
  ["engage with","/ɪnˈɡeɪdʒ wɪð/","认真处理；参与讨论","To become actively involved with an idea or activity.","The chapter engages critically with existing scholarship.","学术写作中表示实质性对话。"],
  ["make sense of","/meɪk sens əv/","理解；理清","To understand something complicated.","The diary helped me make sense of my bodily responses.","自然地描述理解过程。"],
  ["come across","/kʌm əˈkrɒs/","偶然遇见；给人印象","To find by chance or appear in a certain way.","I came across a useful article yesterday.","用于日常叙述信息来源。"],
  ["distinguish","/dɪˈstɪŋɡwɪʃ/","区分","To recognise or explain the difference between things.","We should distinguish representation from manifestation.","概念辨析中的核心动词。"],
  ["revise","/rɪˈvaɪz/","修改；复习","To improve a text or study material again.","I revised the methodology after receiving feedback.","英式英语中兼有修改和复习之意。"]
];

const toWords = (rows, type) => rows.map((r, i) => ({
  id: `${type}-${i + 1}`,
  type,
  term: r[0], phonetic: r[1], chinese: r[2], definition: r[3],
  example: r[4], application: r[5],
  category: type === "research" ? "研究术语" : "生活词汇"
}));

window.WORD_LIBRARY = [...toWords(researchRows, "research"), ...toWords(lifeRows, "life")];
